### ISSUE TITLE
Some issues about Neovim.

### ISSUE THREAD

**Issue by otakutyrant** [nanozuki/CrowsEnv#13]
In ui.lua, nvim-tree's git = {ignore = false} seems meaningless.

There is not any correspond valid config in the documentation: https://github.com/nvim-tree/nvim-tree.lua/blob/master/doc/nvim-tree-lua.txt#L407

**Comment by otakutyrant** [comment]
nvim-tree's `update_cwd` is deprecated. Use `sync_root_with_cwd` instead. See: https://github.com/nvim-tree/nvim-tree.lua/blob/master/doc/nvim-tree-lua.txt#L626

**Comment by nanozuki** [comment]
> There is not any correspond valid config in the documentation: https://github.com/nvim-tree/nvim-tree.lua/blob/master/doc/nvim-tree-lua.txt#L407

> nvim-tree's `update_cwd` is deprecated. Use `sync_root_with_cwd` instead. See: https://github.com/nvim-tree/nvim-tree.lua/blob/master/doc/nvim-tree-lua.txt#L626

There are so many breaking change in nvim-tree, so my config may not suit for current version. All function I used is fine, but thanks for your reminding, I'll check the document.

**Comment by nanozuki** [comment]
> I found out that your config do not include any `number` or `relativenumber`. Why?

You can search these in github webpage. You will find:
https://github.com/nanozuki/CrowsEnv/blob/d65b3f016fbfd92a11c789e35f33ff7316446d0c/dot_config/nvim/lua/config/editor.lua#L8

**Comment by otakutyrant** [comment]
Here is a tip! You can use `number` and `relativenumber` in nvim-tree config too.

**Comment by nanozuki** [comment]
> Here is a tip! You can use `number` and `relativenumber` in nvim-tree config too.

Oh, I got it, thanks!
